name: Deploy to Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
        
    - name: Install dependencies
      run: |
        cd server
        npm ci --production
        
    - name: Run tests
      run: |
        cd server
        npm test || echo "No tests found"
        
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      run: |
        # Make scripts executable
        chmod +x deploy.sh fix-bot-conflict.sh setup-webhook.sh
        
        # Deploy to server
        ./deploy.sh main ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_USER }}
        
    - name: Setup webhook
      if: github.ref == 'refs/heads/main'
      run: |
        ./setup-webhook.sh ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_USER }}
        
    - name: Verify deployment
      if: github.ref == 'refs/heads/main'
      run: |
        # Wait for services to start
        sleep 30
        
        # Check API health
        curl -f http://${{ secrets.SERVER_IP }}:3001/api/health || exit 1
        
        # Check webhook status
        curl -f http://${{ secrets.SERVER_IP }}:3001/api/webhook/status || exit 1
        
        echo "✅ Deployment successful!"